### ISSUE TITLE
Missing Microsoft Band and Gemsense Connector

### ISSUE THREAD

**Issue by coolioxlr** [ibm-wearables-sdk-for-mobile/ibm-wearables-swift-sdk#3]
I check the ios demo app and it only has SensorTag connector. 
Also can't get the app to run.

**Comment by cirilla** [comment]
Hi

the Microsoft Band and Gemsense Connectors can be found here:
https://github.com/ibm-wearables-sdk-for-mobile/ibm-wearables-swift-sdk/tree/master/Connectors

please follow the wiki page for setup your project using third part SDK
https://github.com/ibm-wearables-sdk-for-mobile/ibm-wearables-swift-sdk/wiki/Setup 

Thanks
