### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [ibm-wearables-sdk-for-mobile/ibm-wearables-swift-sdk#4]
Hi,
It's will be great to add [Carthage](https://github.com/Carthage/Carthage) support

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍

**Comment by cirilla** [comment]
Hi

We will consider your suggestion.

Thank you
